server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pay_strategy?useUnicode=true&characterEncoding=utf-8&useSSL=true
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456

logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    com.liwei.paystrategy.mapper: debug
